name: Tests

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - feature/**
  workflow_dispatch:
  

jobs:

#   build: 
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#       - name: Docker-compose build
#         run: docker-compose --env-file local.env build --parallel
        # TODO The data is not being cached and passed to the next job. Cache build data for the run.
      
  tests:
#     needs: build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run tests in docker with a local db
      run: make test
    - name: Kill all running containers
      run: make kill_all_containers
