name: Tests

on: 
  pull_request:
    branches:
      - main
      - feature/**
  workflow_dispatch:
  

jobs:

#   build: 
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#       - name: Docker-compose build
#         run: docker-compose --env-file local.env build --parallel
        # TODO The data is not being cached and passed to the next job. Cache build data for the run.
      
  tests:
#     needs: build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run docker-compose test
      run: docker-compose --env-file local.env -f docker-compose.yaml run --rm test
    - name: Kill all running containers
      run: docker ps -q | xargs -r docker kill
